version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-storybook
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - /usr/src/node_modules
      - .:/usr/src
    environment:
      - NODE_ENV=development